package de.madtracki.transaktor.ui.theme

import androidx.compose.ui.graphics.Color

// Light mode
val primaryLight = Color(0xFF007A56)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2D5A4F)
val onPrimaryContainerLight = Color(0xFFA6BDBD)
val secondaryLight = Color(0xFF44664B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF7AA692)
val onSecondaryContainerLight = Color(0xFF22432B)
val tertiaryLight = Color(0xFF38665D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF5A8875)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFA7322A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFC94A40)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFECFEF6)
val onBackgroundLight = Color(0xFF1B1C1C)
val surfaceLight = Color(0xFFFAFEFD)
val onSurfaceLight = Color(0xFF1A1C1C)
val surfaceVariantLight = Color(0xFFDEE4E3)
val onSurfaceVariantLight = Color(0xFF424848)
val outlineLight = Color(0xFF727878)
val outlineVariantLight = Color(0xFFC2C8C8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3130)
val inverseOnSurfaceLight = Color(0xFFF1F0F0)
val inversePrimaryLight = Color(0xFFB4CBCB)
val surfaceDimLight = Color(0xFFDADAD9)
val surfaceBrightLight = Color(0xFFFAF9F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3F3)
val surfaceContainerLight = Color(0xFFEEEEED)
val surfaceContainerHighLight = Color(0xFFE9E8E7)
val surfaceContainerHighestLight = Color(0xFFE3E2E2)

// Dark mode

val primaryDark = Color(0xFFB4CBCB)
val onPrimaryDark = Color(0xFF1F3434)
val primaryContainerDark = Color(0xFF384D4D)
val onPrimaryContainerDark = Color(0xFFA6BDBD)
val secondaryDark = Color(0xFFAAD0AF)
val onSecondaryDark = Color(0xFF153720)
val secondaryContainerDark = Color(0xFF8BB091)
val onSecondaryContainerDark = Color(0xFF22432B)
val tertiaryDark = Color(0xFFA0D0C6)
val onTertiaryDark = Color(0xFF013730)
val tertiaryContainerDark = Color(0xFF517F76)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFFEE6559)
val onErrorContainerDark = Color(0xFF520003)
val backgroundDark = Color(0xFF121413)
val onBackgroundDark = Color(0xFFE3E2E1)
val surfaceDark = Color(0xFF121414)
val onSurfaceDark = Color(0xFFE3E2E2)
val surfaceVariantDark = Color(0xFF424848)
val onSurfaceVariantDark = Color(0xFFC2C8C8)
val outlineDark = Color(0xFF8C9292)
val outlineVariantDark = Color(0xFF424848)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E2)
val inverseOnSurfaceDark = Color(0xFF2F3130)
val inversePrimaryDark = Color(0xFF4D6262)
val surfaceDimDark = Color(0xFF121414)
val surfaceBrightDark = Color(0xFF383939)
val surfaceContainerLowestDark = Color(0xFF0D0E0E)
val surfaceContainerLowDark = Color(0xFF1A1C1C)
val surfaceContainerDark = Color(0xFF1E2020)
val surfaceContainerHighDark = Color(0xFF292A2A)
val surfaceContainerHighestDark = Color(0xFF343535)







